#!/usr/bin/env ruby

require 'base64'

File.open(__dir__ + '/../src/sounds/generated_sounds.ts', 'w') do |output|
  output << "// This file is generated by scripts/convert_sounds.rb.\n"

  Dir.glob(__dir__ + '/../assets/sounds/*.mp3') do |filename|
    contents = File.read(filename)
    output << "export const #{File.basename(filename, '.*')} = `#{Base64.encode64(contents)}`;\n"
  end
end
